language: python

matrix:
  include:
    - os: linux
      sudo: required
      python: 3.6
      dist: xenial

    - os: osx
      osx_image: xcode10
      language: generic
      env: PYTHON=36

install:
  - pip install pytest pytest-cov coveralls
  - pip install .

script:
  - pytest --cov=package_name tests

after_success:
  - coveralls

notifications:
  email: true